---
version: '3'

networks:
  symfony:
    driver: bridge

services:
  symfony:
    container_name: symfony
    image: docker.io/bitnami/symfony:latest
    ports:
      - '9000:9000'
    environment:
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton:"6.2.*"
      - SYMFONY_DATABASE_HOST=mysql
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=symfony_master
      - SYMFONY_DATABASE_NAME=poll
      - SYMFONY_DATABASE_PASSWORD_FILE=/run/secrets/user.pwd
      - PHP_FPM_LISTEN_ADDRESS=0.0.0.0:9000
      - PHP_DATE_TIMEZONE=Asia/Yekaterinburg
      - PHP_ENABLE_OPCACHE=yes
    command: /opt/bitnami/scripts/php/run.sh
    volumes:
      - '../symfony:/app:rw'
      - ./db/secrets/user.pwd:/run/secrets/user.pwd:ro
      - ./scripts/symfony/entrypoint.sh:/opt/bitnami/scripts/symfony/entrypoint.sh:ro
      - ./scripts/symfony/init.sh:/opt/bitnami/scripts/symfony/init.sh:ro
    networks:
      - symfony
    depends_on:
      - mysql

  node_builder:
    container_name: node_builder
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    command: sh -c 'npm install reactstrap --legacy-peer-deps && npm run dev; exit 0'
    volumes:
      - '../symfony:/app:rw'
    depends_on:
      - symfony

  node:
    container_name: node
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:16
    command: sh -c 'yarn install --non-interactive; npm run build; node /app/.output/server/index.mjs'
    environment:
      - NUXT_TELEMETRY_DISABLED=1
    ports:
      - 3000:3000
    volumes:
      - '../test_nuxt:/app:rw'
    depends_on:
      - symfony

  nginx:
    container_name: nginx
    image: docker.io/bitnami/nginx:latest
    ports:
      - "81:80"
      - "443:8443"
    networks:
      - symfony
    depends_on:
      - symfony
    volumes:
      - ./../symfony/public:/app/public
      - ./nginx/server_blocks:/opt/bitnami/nginx/conf/server_blocks:ro
      - ./nginx/logs:/opt/bitnami/nginx/logs

  mysql:
    container_name: mysql
    image: docker.io/bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/root.pwd
      - MYSQL_PASSWORD_FILE=/run/secrets/user.pwd
      - MYSQL_REPLICATION_PASSWORD_FILE=/run/secrets/replica.pwd
      - MYSQL_USER=symfony_master
      - MYSQL_DATABASE=poll
      - MYSQL_COLLATE=utf8mb4_unicode_ci
      - MYSQL_CHARACTER_SET=utf8mb4
      - MYSQL_REPLICATION_USER=slave_read_user
    ports:
      - "3307:3306"
    volumes:
      - ./db/secrets:/run/secrets:ro
      - ./db/mysql:/bitnami/mysql:rw
    networks:
      - symfony

  mailhog:
    container_name: mailhog
    image: docker.io/mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    depends_on:
      - symfony
      - mysql
    networks:
      - symfony

volumes:
  nginx_log:
  symfony_log:
  db:
    driver: local
