# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        flysystem_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.upload_question_filesystem
                root_url: "%question_upload_url%"
                cache_prefix: media/cache
                visibility: public
        flysystem_variant_resolver:
            flysystem:
                filesystem_service: oneup_flysystem.upload_variant_filesystem
                root_url: "%variant_upload_url%"
                cache_prefix: media/cache
                visibility: public
    #    cache: ~
    #    data_loader: ~

    loaders:
        question_flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.upload_question_filesystem
        variant_flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.upload_variant_filesystem
    # your filter sets are defined here
    twig:
        mode: lazy
    filter_sets:
        cache: ~
        question_thumb:
            cache: flysystem_resolver
            data_loader: question_flysystem_loader
            quality: 50
            filters:
                thumbnail: { size: [120, 120], mode: outbound }

        question_preview:
            cache: flysystem_resolver
            data_loader: question_flysystem_loader
            quality: 75
            filters:
                thumbnail: { size: [ 240, 240 ], mode: outbound }

        question_detail:
            cache: flysystem_resolver
            data_loader: question_flysystem_loader
            quality: 90
            filters:
                thumbnail: { size: [ 480, 480 ], mode: outbound }

        variant_detail:
            cache: flysystem_variant_resolver
            data_loader: variant_flysystem_loader
            quality: 90
            filters:
                thumbnail: { size: [ 480, 480 ], mode: outbound }
        variant_preview:
            cache: flysystem_variant_resolver
            data_loader: variant_flysystem_loader
            quality: 75
            filters:
                thumbnail: { size: [ 240, 240 ], mode: outbound }
        variant_thumb:
            cache: flysystem_variant_resolver
            data_loader: variant_flysystem_loader
            quality: 50
            filters:
                thumbnail: { size: [ 40, 40 ], mode: outbound }

